### ISSUE TITLE
partly_adequate_configuration_manager bug

### ISSUE THREAD

**Issue by opuruhaji** [Reispfannenfresser/partly-adequate-mapvote#22]
if load partly_adequate_configuration_manager on server then
[dofaminovy|2|STEAM_0:0:235310125] Lua Error:

[libk] addons/libk/lua/libk/client/cl_libk_client.lua:3: Tried to resolve an already rejected deferred!
  1. error - [C]:-1
   2. Resolve - addons/libk/lua/libk/shared/1_sh_promises.lua:179
    3. fn - addons/libk/lua/libk/client/cl_libk_client.lua:3
     4. unknown - addons/ulib/lua/ulib/shared/hook.lua:109
in addition, TTT2 hud is disappears

**Comment by Reispfannenfresser** [comment]
Hello there,
thank you for reporting an issue. It seems like you missed the issue templates though and your issue is lacking some crucial information that I'd need for debugging.

Please follow [this Template](https://github.com/Partly-Adequate/partly-adequate-mapvote/issues/new?assignees=Reispfannenfresser&labels=bug&template=bug_report.md).

**Comment by Reispfannenfresser** [comment]
I don't think I can fix this, if you don't provide the requested information. I'll close this issue for now.
